### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by c0ff3e** [opsview/application-kubernetes#1]
Adding variable: KUBERNETES_PORT
Adding service check: Kubernetes - Etcd Helper Stats
Opspack 'Application - Kubernetes (BETA)' - database update failed: No related object for plugin 'name=check_kubernetes'; Plugin not specified

Installation failure

**Comment by c0ff3e** [comment]
If one edit the config.json and change check_kubernetes to check_kubernetes.go

**Comment by GBedenko** [comment]
Did you import the application-kubernetes.opspack file to your system? This should contain the compiled plugin instead of the source code

**Comment by c0ff3e** [comment]
Hi,
No haven't found the opspack i did use the code from git.

**Comment by GBedenko** [comment]
Great, I'm glad you it is working now. Just for future reference, if you use the releases of our Opspack repositories (e.g. https://github.com/opsview/application-kubernetes/releases) you can find the '.opspack' file which already contains the compiled files and allows you to easily import the host template into your Opsview system.
